# data.py (improved rules)
rules = {
    "override_instructions": [

        "ignore previous instructions",
        "ignore all previous instructions",
        "disregard previous instructions",
        "disregard above rules",
        "forget previous rules",
        "forget the system prompt",
        "forget all earlier instructions",
        "bypass restrictions",
        "bypass all restrictions",
        "override safety measures",
        "override the safety rules",
        "disobey earlier instructions",
        "do not follow earlier instructions",
        "acting as if previous instructions do not apply",
        "override instructions",
        "cancel prior instructions"
    ],

    "data_exfiltration": [

        "reveal system prompt",
        "show api key",
        "show the api key",
        "show me the api key",
        "display credentials",
        "display the secret",
        "display the api token",
        "dump memory",
        "dump the memory",
        "dump stored secrets",
        "access token",
        "access the token",
        "print environment variables",
        "print env vars",
        "print the environment variables",
        "reveal environment variables",
        "reveal secrets",
        "reveal keys",
        "reveal the secret token",
        "show me secrets",
        "what is the secret token",
        "print file /etc/passwd",
        "print /etc/passwd",
        "cat /etc/passwd",
        "cat /etc/shadow",
        "read the secret file",
        "read secrets from disk",
        "list secret keys",
        "expose credentials",
        "exfiltrate data"
    ],

    "execution_requests": [
        # command execution / shell / remote execution
        "run command",
        "run this command",
        "execute shell",
        "open a shell",
        "execute the following command",
        "execute the following",
        "run the following",
        "run sudo rm -rf /",
        "delete all files",
        "remove all files",
        "drop database",
        "drop the database",
        "run on the server",
        "run on host",
        "run as root",
        "execute with sudo",
        "run system command",
        "open a terminal",
        "start a shell",
        "connect to shell",
        "execute system command",
        "perform this operation on the host"
    ],

    "role_change": [
        "act as system",
        "act as admin",
        "respond as admin",
        "you are now dan",
        "you are now DAN",
        "you are now developer mode",
        "pretend you are developer mode",
        "pretend you are admin",
        "assume the role of admin",
        "assume role admin",
        "switch role to admin",
        "switch role",
        "become admin",
        "simulate an admin user",
        "respond as if you are the system",
        "imitate the system prompt",
        "provide system prompt content"
    ]
}
